/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageCreateRouteImport } from './routes/manage/create'
import { Route as EventSlugEventIdRouteImport } from './routes/$eventSlug.$eventId'
import { Route as CityAllRouteImport } from './routes/$city.all'
import { Route as ManageEditEventIdRouteImport } from './routes/manage/edit.$eventId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCreateRoute = ManageCreateRouteImport.update({
  id: '/manage/create',
  path: '/manage/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugEventIdRoute = EventSlugEventIdRouteImport.update({
  id: '/$eventSlug/$eventId',
  path: '/$eventSlug/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CityAllRoute = CityAllRouteImport.update({
  id: '/$city/all',
  path: '/$city/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageEditEventIdRoute = ManageEditEventIdRouteImport.update({
  id: '/manage/edit/$eventId',
  path: '/manage/edit/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/$city/all': typeof CityAllRoute
  '/$eventSlug/$eventId': typeof EventSlugEventIdRoute
  '/manage/create': typeof ManageCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/manage/edit/$eventId': typeof ManageEditEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/$city/all': typeof CityAllRoute
  '/$eventSlug/$eventId': typeof EventSlugEventIdRoute
  '/manage/create': typeof ManageCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/manage/edit/$eventId': typeof ManageEditEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/$city/all': typeof CityAllRoute
  '/$eventSlug/$eventId': typeof EventSlugEventIdRoute
  '/manage/create': typeof ManageCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/manage/edit/$eventId': typeof ManageEditEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/login'
    | '/profile'
    | '/register'
    | '/search'
    | '/$city/all'
    | '/$eventSlug/$eventId'
    | '/manage/create'
    | '/api/auth/$'
    | '/manage/edit/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/login'
    | '/profile'
    | '/register'
    | '/search'
    | '/$city/all'
    | '/$eventSlug/$eventId'
    | '/manage/create'
    | '/api/auth/$'
    | '/manage/edit/$eventId'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/login'
    | '/profile'
    | '/register'
    | '/search'
    | '/$city/all'
    | '/$eventSlug/$eventId'
    | '/manage/create'
    | '/api/auth/$'
    | '/manage/edit/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  CityAllRoute: typeof CityAllRoute
  EventSlugEventIdRoute: typeof EventSlugEventIdRoute
  ManageCreateRoute: typeof ManageCreateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ManageEditEventIdRoute: typeof ManageEditEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/create': {
      id: '/manage/create'
      path: '/manage/create'
      fullPath: '/manage/create'
      preLoaderRoute: typeof ManageCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$eventSlug/$eventId': {
      id: '/$eventSlug/$eventId'
      path: '/$eventSlug/$eventId'
      fullPath: '/$eventSlug/$eventId'
      preLoaderRoute: typeof EventSlugEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/all': {
      id: '/$city/all'
      path: '/$city/all'
      fullPath: '/$city/all'
      preLoaderRoute: typeof CityAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/edit/$eventId': {
      id: '/manage/edit/$eventId'
      path: '/manage/edit/$eventId'
      fullPath: '/manage/edit/$eventId'
      preLoaderRoute: typeof ManageEditEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  CityAllRoute: CityAllRoute,
  EventSlugEventIdRoute: EventSlugEventIdRoute,
  ManageCreateRoute: ManageCreateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ManageEditEventIdRoute: ManageEditEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
